Repository Kuadrant/testsuite, pull requests merged in 2024-09, with the labels that each got.

#524 Remove pytest-asyncio lib
  pyproject.toml
Labels: refactor

#526 Remove xfail due to gateway listeneners bug being fixed
  testsuite/tests/singlecluster/gateway/reconciliation/test_gateway_listeners_dns.py
Labels: good first issue

#516 Add geo load-balancing tests
  config/settings.local.yaml.tpl
  testsuite/capabilities.py
  testsuite/config/__init__.py
  testsuite/config/exposer.py
  testsuite/config/openshift_loader.py
  testsuite/kuadrant/policy/dns.py
  testsuite/tests/conftest.py
  testsuite/tests/multicluster/conftest.py
  testsuite/tests/multicluster/load_balanced/__init__.py
  testsuite/tests/multicluster/load_balanced/conftest.py
  testsuite/tests/multicluster/load_balanced/test_load_balanced_geo.py
  testsuite/tests/multicluster/load_balanced/test_unsupported_geocode.py
  testsuite/tests/multicluster/test_simple_strategy.py
  testsuite/tests/singlecluster/authorino/operator/clusterwide/conftest.py
  testsuite/tests/singlecluster/authorino/operator/clusterwide/test_all_namespace_api_key.py
  testsuite/tests/singlecluster/authorino/operator/clusterwide/test_wildcard_collision.py
  testsuite/tests/singlecluster/conftest.py
  testsuite/utils.py
Labels: Test case, DNS

#534 Assert IPs returned in round-robin fashion in the multicluster test
  testsuite/tests/multicluster/test_simple_strategy.py
Labels: enhancement

#536 Add flag for html generation
  Makefile
Labels: enhancement, good first issue

#520 Add test for invalid credentials in dns provider
  testsuite/kuadrant/policy/dns.py
  testsuite/kubernetes/secret.py
  testsuite/tests/singlecluster/gateway/dnspolicy/__init__.py
  testsuite/tests/singlecluster/gateway/dnspolicy/test_invalid_credentials.py
Labels: Test case

#533 Update default settings
  config/settings.yaml
Labels: enhancement

#537 Skip geo test if dns not configured
  testsuite/tests/multicluster/load_balanced/conftest.py
Labels: enhancement

#529 Add gateway listeners scaling test
  testsuite/gateway/gateway_api/gateway.py
  testsuite/kuadrant/policy/__init__.py
  testsuite/kuadrant/policy/dns.py
  testsuite/tests/singlecluster/gateway/test_scale_listeners.py
Labels: Test case, DNS

#540 Improve assert on unsupported geo test
  testsuite/tests/multicluster/load_balanced/test_unsupported_geocode.py
Labels: enhancement

#511 Add Kuadrant version to pytest report
  testsuite/capabilities.py
  testsuite/tests/conftest.py
Labels: enhancement
