Repository Kuadrant/testsuite, pull requests merged in 2025-07, with the labels that each got.

#697 Update change_targetref tests to fix azure DNS issue
  testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/conftest.py
Labels: refactor

#699 Fix invalid issuer test
  testsuite/kubernetes/client.py
  testsuite/tests/singlecluster/gateway/reconciliation/test_invalid_issuer_reference.py
Labels: bug

#710 Replace 2gw64listeners test with kubeburner
  scale_test/max-gateway-listeners/README.md
  scale_test/max-gateway-listeners/config.yaml
  scale_test/max-gateway-listeners/templates/aws-credentials.yaml
  scale_test/max-gateway-listeners/templates/azure-credentials.yaml
  scale_test/max-gateway-listeners/templates/dnspolicy.yaml
  scale_test/max-gateway-listeners/templates/gateway.yaml
  scale_test/max-gateway-listeners/templates/gcp-credentials.yaml
  scale_test/max-gateway-listeners/templates/httpbin-deployment.yaml
  scale_test/max-gateway-listeners/templates/httpbin-service.yaml
  scale_test/max-gateway-listeners/templates/httproute.yaml
  scale_test/max-gateway-listeners/test.sh
  testsuite/tests/singlecluster/gateway/test_scale_listeners.py
Labels: Test case
