Repository Kuadrant/testsuite, pull requests merged in 2025-04, with the labels that each got.

#641 Add tests for changing targetRef field in policies
  testsuite/gateway/gateway_api/gateway.py
  testsuite/httpx/__init__.py
  testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/conftest.py
  testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_authpolicy_target_ref.py
  testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_dnspolicy_target_ref.py
  testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_ratelimitpolicy_target_ref.py
  testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_tlspolicy_target_ref.py
Labels: Test case, DNS, refactor

#665 Update failing change_targetref tests
  testsuite/httpx/__init__.py
  testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_authpolicy_target_ref.py
  testsuite/tests/singlecluster/gateway/reconciliation/change_targetref/test_update_tlspolicy_target_ref.py
Labels: refactor

#667 Update httproute-delete test
  testsuite/tests/singlecluster/reconciliation/test_httproute_delete.py
Labels: refactor

#666 Fix/refactor authorino metadata tests
  testsuite/tests/singlecluster/authorino/caching/metadata/test_caching.py
  testsuite/tests/singlecluster/authorino/caching/metadata/test_not_cached.py
  testsuite/tests/singlecluster/authorino/caching/metadata/test_ttl.py
  testsuite/utils.py
Labels: bug, refactor
